### PR TITLE
Add continuous integration

### PR DESCRIPTION
**Pull request by israpps**
u can squash and merge to keep git history clean

### CODE REVIEW

**Comment by blckbearx** [comment]
Hi, may I ask what are the benefits of adding CI/CD?

**Comment by israpps** [comment]
> Hi, may I ask what are the benefits of adding CI/CD?

Compile the project on the fly without needing to do it manually on the PC..

Also, since it uses docker you can keep the binaries with up to date PS2DEV toolchain without updating local build

**Comment by blckbearx** [comment]
Great, that's nice.
Is this automated in any sort of way or do I need to trigger the build manually?
Because if it's triggered by pushing commits for example or merging PRs, I don't think it's a good idea, but if I can trigger it manually it is good as I can make sure I publish builds that I have tested and know that work.

**Comment by israpps** [comment]
> Great, that's nice. Is this automated in any sort of way or do I need to trigger the build manually? Because if it's triggered by pushing commits for example or merging PRs, I don't think it's a good idea, but if I can trigger it manually it is good as I can make sure I publish builds that I have tested and know that work.

it triggers with every commit...

the releases are pushed into the `latest` tag, keeping those binaries separated from the releases pushed by you.

Workflow can also be executed bu pull requests, but in that case it won´t push releases...

there is also manual dispatch of workflow 

there is nothing to worry about...

OPL, uLaunchELF and lots of widely consumed projects also use this

**Comment by israpps** [comment]
If you wanna make the workflow only trigger manually then:
```diff

name: "compile and release"
on:
  workflow_dispatch:
-#  pull_request:
+  pull_request:
  repository_dispatch:
    types: [release_workflow]
-  push:
```

by doing this:

releases will be only produced if you trigger the workflow manually from the actions tab

it will also produce binaries for Pull requests

**Comment by blckbearx** [comment]
Hi, sorry for the late reply, I had a busy week.
I've been reading a bit about CI/CD and I don't see its use in this project as this is a small piece of software, it's just a one-trick pony. I can understand the point of having CI/CD on projects like OPL and wLE, but for a project the size of pops-smb-config it's just a waste of computing power.
Thanks for showing interest in the project but I don't think this changes fit the project.
I wasn't planning on closing the pull request after my reply (just because maybe in the future this may become an important change in the project if it somehow grows) but I see you already did it.

**Pull request closed without merging**
